services:
  postgres:
    environment:
      - POSTGRES_DB=dbmaster
      - POSTGRES_USER=dbmasteruser
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: public.ecr.aws/docker/library/postgres:16.4
    ports:
      - "5432:5432"
