# Application Configuration
spring:
  application:
    name: foosball
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://ls-3cd9e093f05f5c4d801b58031197f04063b55800.cmldxjsfqvn4.us-east-1.rds.amazonaws.com:5432/dbmaster
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    default-schema: foosball
  data:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
          type: trace
          hbm2ddl:
            auto: validate

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native

# Logging Configuration
logging:
  level:
    com.thonbecker.foosball: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Monitoring/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    default-timeout: 180s
