name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  BP_JVM_VERSION: 21
  IMAGE_NAME: "foosball"
  BUILDPACK_JAVA: "gcr.io/paketo-buildpacks/amazon-corretto"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build Docker Image
        run: |
          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ env.IMAGE_NAME }} \
            -Dspring-boot.build-image.buildpacks=${{ env.BUILDPACK_JAVA }}
        env:
          BP_JVM_VERSION: ${{ env.BP_JVM_VERSION }}

      - name: Authenticate to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p0w8z2j2
          docker tag foosball:latest public.ecr.aws/p0w8z2j2/foosball:latest
          docker push public.ecr.aws/p0w8z2j2/foosball:latest
